version: "3.8"

services:
  postgres:
    container_name: yawoendb
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: yawoendb
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/data

volumes:
  dbdata: